recipes-devtools/erlang/erlang-19.0-manifest.inc, recipes-devtools/erlang/erlang-19.0.inc, recipes-devtools/erlang/erlang-native_19.0.bb, recipes-devtools/erlang/erlang_19.0.bb, scripts/contrib/erlang/generate-manifest
This is a direct copy of OTP 18.3.4 support.  The manifest might need to be tweaked, but it appears to be working
=> erlang: add 19.0 recipes

recipes-devtools/erlang/erlang.inc
Current build is broken as patches will be applied to
"${WORKDIR}/otp-OTP-${PV}" while git actually checks out the code in
"${WORKDIR}/git". This patch fixes it by applying patches to
"${WORKDIR}/git".
Signed-off-by: Oscar Andreasson <oscar.andreasson@pelagicore.com>
=> erlang.inc: Fix paths

recipes-devtools/erlang/erlang.inc
With the introduction of recipe-specific sysroots in pyro, the
build-time dependencies has to be explicitly declared.
Signed-off-by: Henrik Nymann Jensen <hnje@prevas.dk>
=> erlang.inc: Declare openssl-native as build-time dependency

classes/rebar3.bbclass
get_erlang_erts now has the same level of indentation
as the other functions (e.g, get_erlang_release).
=> rebar3.bbclass: fix indentation

classes/rebar3.bbclass
The previous method of extracting erts is error-prone. This way is more direct.
=> rebar3: improve ERLANG_ERTS extraction

recipes-core/erlinit/erlinit_git.bb
Hello,
[The erlinit git repository](https://github.com/nerves-project/erlinit) has changed the name of the branches, from "master" to "main", causing errors in the fetch step:
```
ERROR: erlinit-1.6.0-gitAUTOINC+53b0a4dfc5-r0 do_fetch: Fetcher failure: Unable to find revision 53b0a4dfc5aab5f883652527e29e2db39ac546ae in branch master even from upstream
ERROR: erlinit-1.6.0-gitAUTOINC+53b0a4dfc5-r0 do_fetch: Fetcher failure for URL: 'git://github.com/nerves-project/erlinit;branch=master'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: [...]/build/tmp/work/aarch64-poky-linux/erlinit/1.6.0-gitAUTOINC+53b0a4dfc5-r0/temp/log.do_fetch.26591
ERROR: Task ([...]/poky/meta-erlang/recipes-core/erlinit/erlinit_git.bb:do_fetch) failed with exit code '1'
```
This patch fixes …
=> erlinit: fix download url

classes/mix.bbclass
Without this change building a mix release does not work on meta-erlang master, since the erts path is wrong. The directory erts-<version> is now appended to it.
Tested with erlang 23.2.1 and elixir 1.11.2
=> mix.bbclass: Fix mix release erts path

recipes-devtools/erlang/erlang.inc, recipes-devtools/erlang/files/otp-0002-Remove-rpath.patch
When building erlang-native, rpath might lead to host contamination.
Borrowed from [1].
1:
https://src.fedoraproject.org/rpms/erlang/blob/rawhide/f/otp-0002-Remove-rpath.patch
=> erlang: remove rpath

recipes-devtools/erlang/erlang.inc
erts is an application that dialyzer uses if configured for (1).
1:
https://github.com/erlang/otp/blob/master/lib/dialyzer/src/dialyzer_cl_parse.erl#L346
=> erlang: allowing using dialyzer for native and nativesdk

recipes-core/epmd/epmd.inc
Introduce TARGET_SYS_GNU with the fixed TARGET_SYS. So the install step
can find the correct binary.
Change-Id: Ibd7eb04651dd705f1fcfce29dcf04fa02b05b974
=> epmd: Erlang build appends '-gnu' to TARGET_SYS

recipes-devtools/erlang/erlang.inc, recipes-devtools/erlang/erlang_24.0.2.bb
YP/OE hardknott uses autoconf 2.71 while Erlang/OTP still uses autoconf
2.69 leading to some potential problems. One of then is about the macro
AC_EGREP_CPP which expects the EGREP variable be filled.
The issue [1] has more details about the problem. For while the
erlang.inc exports the EGREP variable to fix the problem when compiling
erlang-native that was not able to find the correct Openssl libraries in
the sysroot-native folder.
Moreover, this commit also introduce the use of '--with-ssl-zlib' to fix
a potential host contamination when building for native and native-sdk.
1: https://github.com/erlang/otp/issues/4821
=> erlang: export EGREP to make AC_EGREP_CPP works

recipes-database/couchdb/couchdb_3.1.1.bb, recipes-database/couchdb/couchdb_3.1.2.bb
https://docs.couchdb.org/en/stable/whatsnew/3.1.html#version-3-1-2
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-38295
=> couchdb: 3.1.1 -> 3.1.2

recipes-connectivity/rabbitmq/rabbitmq-server_3.9.8.bb
With the Yocto honister release the format of variables has changed. Follow up on that.
=> rabbitmq: fix REDEPENDS variable

recipes-database/couchdb/couchdb.inc
Apache Foundation keeps a mirror where has all past releases from
couchdb project.
=> couchdb: use APACHE_MIRROR as SRC_URI

classes/mix.bbclass, classes/rebar3.bbclass
Usually the do_fetch is allowed to fetch external resources. But for mix
and rebar3 recipes that happens on do_configure task due how these tools
works.
This enables network support for do_configure task [1].
1: https://docs.yoctoproject.org/dev/migration-guides/migration-4.0.html#fetching-changes
=> Enable network support for do_configure task

recipes-connectivity/vernemq/files/Makefile.c_src.bcrypt, recipes-connectivity/vernemq/files/Makefile.c_src.eleveldb, recipes-connectivity/vernemq/files/Makefile.c_src.vmq_passwd, recipes-connectivity/vernemq/files/build_deps.sh.eleveldb, recipes-connectivity/vernemq/files/rebar.config.eleveldb, recipes-connectivity/vernemq/files/vars.config, recipes-connectivity/vernemq/files/vernemq-volatiles.conf, recipes-connectivity/vernemq/files/vernemq.conf, recipes-connectivity/vernemq/files/vernemq.init, recipes-connectivity/vernemq/files/vernemq.service, recipes-connectivity/vernemq/files/vm.args, recipes-connectivity/vernemq/files/volatiles.99_vernemq, recipes-connectivity/vernemq/vernemq_1.12.5.bb
Add vernemq. Not fully tested yet. But the recipe builds fine.
I've used a x86-64 machine. As I suspect the eleveldb will not work for x86-32bits.
What is missing:
https://github.com/meta-erlang/meta-erlang/issues/158
=> vernemq: introduce vernemq 1.12.5

recipes-devtools/yanger/files/0001-Add-install-rule.patch, recipes-devtools/yanger/files/environment.d-yanger.sh, recipes-devtools/yanger/files/yanger.sh, recipes-devtools/yanger/yanger_git.bb
yanger does not provide a make install rule. So this commit creates that
rule in order to install the project. This is important when using
yanger with nativesdk.
=> yanger: install yanger artifacts

recipes-devtools/erlang_ls/erlang-ls_0.44.1.bb
Use 0.44.1 as it looks vscode has a better support for it.
=> erlang_ls: 0.28.0 -> 0.44.1

recipes-devtools/erlang_ls/erlang-ls_0.44.1.bb
Use 0.44.1 as it looks vscode has a better support for it.
=> erlang_ls: 0.46.2 -> 0.44.1

recipes-devtools/livebook/livebook_0.5.2.bb
livebook has some use cases where the user could install additional elixir dependencies. And mix is necessary to be installed.
=> livebook: add elixir-mix as RDEPENDS

recipes-core/erlinit/erlinit_git.bb, recipes-devtools/livebook/livebook_0.10.0.bb, recipes-devtools/rebar/rebar_git.bb, recipes-devtools/relsync/relsync_git.bb, recipes-devtools/relx/relx_git.bb
This change is necessary to align with conventions from Yocto/OE projects. Also it fixes problems when the packages are processing using SBOM scanners for example.
=> Fix PV from '-' to '+'

recipes-connectivity/rabbitmq/rabbitmq-server_3.10.25.bb
With Update of elixir "elixir: add 1.15.2" (7ec3cada6a555e172134f927cd4311bfc1b29fb6), the build for rabbitmq-server fails. Since it work with the newest 3.10.x version update update to this.
=> rabbitmq: 3.10.24 -> 3.10.25

classes/atomvm.bbclass, classes/mix.bbclass, classes/rebar.bbclass, classes/rebar3-brokensep.bbclass, classes/rebar3.bbclass, recipes-extended/mozjs/mozjs-91_91.13.0.bb
This is useful if you are building from a SRC repository where the mix / erlang project is in a subdirectory of the repo.
=> Allow B to be set externally

recipes-devtools/elixir/elixir_1.16.3.bb
Would be useful for anyone still using kirkstone but would like a 1.16.3 version of Elixir.
=> Add in elixir_1.16.3.bb from upstream

recipes-devtools/erlang/erlang.inc
The prefix '-gnu' is only valid por x86 based builds. When ARM or other that prefix could be other.
=> erlang: find config.h based on TARGET_SYS

recipes-devtools/elixir/elixir.inc, recipes-devtools/elixir/files/run-ptest
ptest is interesting for running elixir unit test on target and get results. However, the deterministic build does not work. So, disabling it temporarily (I hope due https://github.com/elixir-lang/elixir/issues/13913).
=> elixir: add ptest support

recipes-database/riak/riak.inc
=> riak: use features_check for pam dependency

recipes-database/couchdb/couchdb_3.4.2.bb, recipes-database/couchdb/files/0001-Fix-cross-compilation-environment-variables-and-use-.patch, recipes-database/couchdb/files/couchdb.init, recipes-database/couchdb/files/couchdb.service, recipes-devtools/rebar/rebar_git.bb
Use quickjs [1] instead mozjs.
mozjs-91 does not support python 3.12.x, thus couchdb for meta-erlang can't usemozjs-91 anymore.
1: https://github.com/apache/couchdb/issues/4448
=> couchdb: bump to 3.4.2
